spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    servlet:
      multipart:
        file-size-threshold: 1MB
        max-file-size: 100MB
        max-request-size: 100MB
    open-in-view: false

jwt:
  accessSecret: ${JWT_ACCESS}
  refreshSecret: ${JWT_REFRESH}
  accessExp: ${ACCESS_EXP}
  refreshExp: ${REFRESH_EXP}